/**
 * Exact DeepSeek V4 Flash Vision image-token arithmetic.
 *
 * Every rule in this module is a line-by-line port of the official
 * `inference/image_processor.py` published by
 * `deepseek-ai/DeepSeek-V4-Flash-Vision-Exp` at the pinned immutable revision
 * recorded below. The golden fixtures in `tests/fixtures/vision-golden.json`
 * are generated by executing that official implementation, so any change here
 * must keep the Node counts byte-identical to the reference output.
 *
 * These arithmetic results back intrinsic-grid estimates, never exact counts
 * of the final request. The official expansion
 * depends on the absolute serialized prompt position (system prompt,
 * chat-template framing, adapter image handles) and on the adapter's final
 * request-image projection — including per-route pixel-budget or image-detail
 * overrides and byte-cap reprojection — none of which is published through a
 * public API, and a projected image can count FEWER tokens than its intrinsic
 * grid suggests. The measurement layer therefore labels image-bearing nodes
 * as estimates and keeps them outside exact rewrite proofs; the 640,000-pixel
 * budget below documents the adapter default rather than establishing
 * exactness.
 */

/** Official projection parameters pinned from the model repository config. */
export const DEEPSEEK_VISION_PROJECTION = Object.freeze({
  sourceRepository: 'deepseek-ai/DeepSeek-V4-Flash-Vision-Exp',
  sourceRevision: '6821d6ad3681a4b137b066b76094fa82ebd0a380',
  /** `vision_patch_size` from the official config. */
  visionPatchSize: 14,
  /** `vision_downsample_ratio` from the official config. */
  visionDownsampleRatio: 3,
  /** `vision_max_n_token`: post-preprocessing cap per image, not a fixed value. */
  visionMaxNTokens: 384,
  /** `vision_min_pixels`: tiny images are upscaled before patching. */
  visionMinPixels: 147_456,
  /** `vision_max_wh_ratio`: wider-than-ratio images are width-clamped. */
  visionMaxWhRatio: 8,
  /**
   * Default per-image pixel budget used by the DeepSeek adapter's normal
   * attachment projection (`DEFAULT_REQUEST_IMAGE_PIXEL_BUDGET` in
   * `@deepseek-ai/dsh-llm-deepseek`). Route overrides remain unobservable to
   * this estimator.
   */
  requestImagePixelBudget: 640_000,
})

/**
 * Fallback charged when durable image metadata cannot be evaluated. It sits
 * near the middle of the official 384-token image budget so one malformed or
 * provider-projected image never makes the surrounding surface unmeasurable.
 */
export const DEEPSEEK_VISION_DEFAULT_IMAGE_TOKENS = 256

/** Stable identity for the deliberately approximate image-token counter. */
export const DEEPSEEK_VISION_IMAGE_ESTIMATOR = Object.freeze({
  id: `${DEEPSEEK_VISION_PROJECTION.sourceRepository}/image-token-estimate`,
  revision: `${DEEPSEEK_VISION_PROJECTION.sourceRevision}:v1`,
})

/** Official `COMPRESS_PAD_TO` alignment constant from image_processor.py. */
const COMPRESS_PAD_TO = 4

/** Aligner-grid facts the official pipeline derives from one image. */
export interface DeepSeekVisionImageGrid {
  readonly nLlmH: number
  readonly nLlmW: number
  readonly bestHeight: number
  readonly bestWidth: number
}

/** One bounded estimate over the four possible stream-alignment residues. */
export interface DeepSeekVisionImageTokenEstimate {
  readonly tokens: number
  readonly upperBoundTokens: number
  readonly source: 'intrinsic-grid' | 'default'
  readonly paddingMinimumTokens?: number
  readonly paddingMaximumTokens?: number
}

/**
 * Whether one image's intrinsic metadata fits the adapter's documented
 * default request pixel budget. This is informational only: estimation also
 * accepts larger valid dimensions because the official processor enforces its
 * own 384-token grid budget.
 */
export function isWithinDeepSeekRequestPixelBudget(width: number, height: number): boolean {
  return width > 0 && height > 0 && width * height <= DEEPSEEK_VISION_PROJECTION.requestImagePixelBudget
}

/**
 * Expand one image into its official token count at a given stream position.
 *
 * The count includes the position-dependent alignment padding from the
 * official `build_image_block`: leading compress pads, the image start and end
 * sentinels, one newline token per grid row, the odd-row pad, and the final
 * two-token alignment pad. `startTokenPos` is the number of tokens already in
 * the stream where this image's block begins, mirroring `len(tokens)` in the
 * official `prepare_vl_inputs`.
 */
export function deepSeekVisionImageTokens(width: number, height: number, startTokenPos: number): number {
  const grid = deepSeekVisionImageGrid(width, height)
  return deepSeekVisionImageBlockTokens(grid.nLlmH, grid.nLlmW, startTokenPos)
}

/**
 * Estimate one image without claiming an exact serialized position or final
 * adapter projection. Valid intrinsic dimensions use the midpoint of the four
 * possible alignment residues. Invalid or unsafe metadata uses the documented
 * fixed fallback. In both cases the official per-image budget is retained as
 * a conservative upper bound.
 */
export function estimateDeepSeekVisionImageTokens(
  width: number,
  height: number,
): DeepSeekVisionImageTokenEstimate {
  if (!Number.isSafeInteger(width) || !Number.isSafeInteger(height)
    || width <= 0 || height <= 0 || !Number.isSafeInteger(width * height)) {
    return Object.freeze({
      tokens: DEEPSEEK_VISION_DEFAULT_IMAGE_TOKENS,
      upperBoundTokens: DEEPSEEK_VISION_PROJECTION.visionMaxNTokens,
      source: 'default',
    })
  }
  try {
    const grid = deepSeekVisionImageGrid(width, height)
    const counts = [0, 1, 2, 3].map(position => (
      deepSeekVisionImageBlockTokens(grid.nLlmH, grid.nLlmW, position)
    ))
    const paddingMinimumTokens = Math.min(...counts)
    const paddingMaximumTokens = Math.max(...counts)
    return Object.freeze({
      tokens: Math.round((paddingMinimumTokens + paddingMaximumTokens) / 2),
      upperBoundTokens: DEEPSEEK_VISION_PROJECTION.visionMaxNTokens,
      source: 'intrinsic-grid',
      paddingMinimumTokens,
      paddingMaximumTokens,
    })
  } catch {
    return Object.freeze({
      tokens: DEEPSEEK_VISION_DEFAULT_IMAGE_TOKENS,
      upperBoundTokens: DEEPSEEK_VISION_PROJECTION.visionMaxNTokens,
      source: 'default',
    })
  }
}

/**
 * Resolve the aligner grid for one image's intrinsic dimensions.
 *
 * Port of the arithmetic path of the official `load_image`: aspect-ratio
 * clamp, minimum-pixel upscale, patch-grid ceiling, and the `safe_resize`
 * budget loop.
 */
export function deepSeekVisionImageGrid(width: number, height: number): DeepSeekVisionImageGrid {
  const { visionPatchSize: patch, visionMaxWhRatio, visionMinPixels } = DEEPSEEK_VISION_PROJECTION
  let effectiveWidth: number = width
  let effectiveHeight: number = height
  if (visionMaxWhRatio !== undefined && effectiveWidth > effectiveHeight * visionMaxWhRatio) {
    effectiveWidth = effectiveHeight * visionMaxWhRatio
  }
  if (effectiveWidth * effectiveHeight > 0 && effectiveWidth * effectiveHeight < visionMinPixels) {
    const ratio = (visionMinPixels / (effectiveWidth * effectiveHeight)) ** 0.5
    effectiveWidth = Math.trunc(effectiveWidth * ratio)
    effectiveHeight = Math.trunc(effectiveHeight * ratio)
  }
  const bestWidth = Math.ceil(effectiveWidth / patch) * patch
  const bestHeight = Math.ceil(effectiveHeight / patch) * patch
  const resolved = safeResize(effectiveHeight, effectiveWidth, bestHeight, bestWidth)
  return Object.freeze({ ...resolved })
}

/**
 * Token count of one expanded image block, port of `build_image_block` length.
 * @internal exported for direct golden-fixture comparison.
 */
export function deepSeekVisionImageBlockTokens(nLlmH: number, nLlmW: number, startTokenPos: number): number {
  const compressPad = COMPRESS_PAD_TO - 1 - startTokenPos % COMPRESS_PAD_TO
  const padH = nLlmH % 2
  const rows = nLlmH + padH
  const rowLen = nLlmW + 1
  const padLast = (Math.floor(rows / 2) * rowLen % 2) * 2
  return compressPad + 1 + rows * rowLen + padLast + 1
}

/** Port of the official `grid_tokens` N-layout occupancy check. */
function gridTokens(bestHeight: number, bestWidth: number): { nLlmH: number, nLlmW: number, numTokens: number } {
  const { visionPatchSize: patch, visionDownsampleRatio: downsample } = DEEPSEEK_VISION_PROJECTION
  const nLlmH = Math.ceil(Math.floor(bestHeight / patch) / downsample)
  const nLlmW = Math.ceil(Math.floor(bestWidth / patch) / downsample)
  let numTokens = nLlmH * (nLlmW + 1) + 2
  if (nLlmH % 2 === 1) {
    numTokens += nLlmW + 1
  }
  numTokens += (Math.floor((nLlmH + 1) / 2) * (nLlmW + 1) % 2) * 2
  return { nLlmH, nLlmW, numTokens }
}

/** Port of the official `solve_resize_ratio` budget solver. */
function solveResizeRatio(
  height: number,
  width: number,
  maxNTokens: number,
): { nLlmH: number, nLlmW: number, bestHeight: number, bestWidth: number } {
  const { visionPatchSize: patch, visionDownsampleRatio: downsample } = DEEPSEEK_VISION_PROJECTION
  const ratio = height / width
  const maxWFloat = Math.sqrt((maxNTokens - 2) / ratio + 0.25) - 0.5
  const maxHFloat = maxWFloat * ratio
  let bestWidth: number
  let bestHeight: number
  if (maxWFloat < 1.0) {
    const maxW = 1
    let maxH = Math.floor((maxNTokens - 2) / (maxW + 1))
    if (maxH % 2 === 1) maxH -= 1
    bestWidth = maxW * patch * downsample
    bestHeight = maxH * patch * downsample
  } else if (maxHFloat < 2.0) {
    const maxH = 2
    const maxW = Math.floor((maxNTokens - 2) / maxH) - 1
    if (maxW <= 1) throw new Error('DeepSeek vision resize solver produced an invalid width')
    bestWidth = maxW * patch * downsample
    bestHeight = maxH * patch * downsample
  } else {
    const maxW = Math.floor(maxWFloat)
    let maxH = Math.floor(maxHFloat)
    if (maxH % 2 === 1) maxH -= 1
    const beta = Math.min(maxW * patch * downsample / width, maxH * patch * downsample / height)
    bestWidth = Math.floor(width * beta / patch) * patch
    bestHeight = Math.floor(height * beta / patch) * patch
  }
  const grid = gridTokens(bestHeight, bestWidth)
  return { nLlmH: grid.nLlmH, nLlmW: grid.nLlmW, bestHeight, bestWidth }
}

/** Port of the official `safe_resize` loop with the compress-pad budget. */
function safeResize(
  height: number,
  width: number,
  initialBestHeight: number,
  initialBestWidth: number,
): { nLlmH: number, nLlmW: number, bestHeight: number, bestWidth: number } {
  const { visionMaxNTokens } = DEEPSEEK_VISION_PROJECTION
  let budget = visionMaxNTokens - (COMPRESS_PAD_TO - 1)
  let grid = gridTokens(initialBestHeight, initialBestWidth)
  let bestHeight = initialBestHeight
  let bestWidth = initialBestWidth
  while (grid.numTokens > budget) {
    const solved = solveResizeRatio(height, width, budget)
    grid = gridTokens(solved.bestHeight, solved.bestWidth)
    bestHeight = solved.bestHeight
    bestWidth = solved.bestWidth
    budget -= 1
  }
  return { nLlmH: grid.nLlmH, nLlmW: grid.nLlmW, bestHeight, bestWidth }
}
