/**
 * sync-hosts.mjs —— 从 hosts.mjs（唯一事实源）下发本仓全部宿主声明写点。
 *
 * 以 dsh-date-wrapper/scripts/sync-hosts.mjs（9 语版）为底本，按 cci 拓扑改编
 * （enum-peer 家族范式；审计 B1/B3/B4 定案）：
 * 1. **三写点**：root package.json（闸门面：engines.dsh + 4 client peer 枚举）→
 *    packages/selector/package.json（内部一致性面：engines.dsh + 19 dsh-* peer 枚举
 *    + version 镜像 root）→ packages/selector/dsh.plugin.json（engines.dsh +
 *    version 镜像 **root**——manifest 镜像源是 root package.json，不是同目录
 *    selector，见 findings §A0 反证）。
 * 2. **9 语 README** 管理块（md/zh/de/es/fr/it/ru/ja/ko 实名文件，README.zh.md
 *    非 zh-CN）。工具只插/更新管理块，不清理历史兼容句（人工删除清单见
 *    plan tasks task_1.5：README.md:50-59/:88-90、README.zh.md:50/:77）。
 * 3. 双模式：默认只校验（exit 1 = 有漂移）；`--write` 实际写盘。
 *
 * 用法：node scripts/sync-hosts.mjs [--write]
 */
import { readFile, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import assert from 'node:assert/strict'
import { supportedHosts, peerRange, developmentHost, rootHostPeers, selectorDshPeers } from './hosts.mjs'

const ROOT = new URL('..', import.meta.url)
const write = process.argv.includes('--write')
const read = (rel) => readFile(new URL(rel, ROOT), 'utf8')

// ── 0. hosts.mjs 自检 ────────────────────────────────────────────────────────
const RC_RE = /^\d+\.\d+\.\d+-rc\.\d+$/
assert(supportedHosts.length > 0, 'supportedHosts 不得为空')
assert.equal(new Set(supportedHosts).size, supportedHosts.length, 'supportedHosts 有重复项')
for (const v of supportedHosts) assert(RC_RE.test(v), `非 rc 版本混入枚举: ${v}（本插件只收 rc）`)
assert(supportedHosts.includes(developmentHost), 'developmentHost 必须在 supportedHosts 内')

// ── 1. root package.json：闸门面（engines.dsh + 4 client peer） ─────────────
const pkgUrl = new URL('package.json', ROOT)
const pkgOriginal = await read('package.json')
const pkg = JSON.parse(pkgOriginal)
pkg.engines ??= {}
pkg.engines.dsh = peerRange
pkg.peerDependencies ??= {}
pkg.peerDependenciesMeta ??= {}
for (const name of rootHostPeers) {
  pkg.peerDependencies[name] = peerRange
  // optional：缺失不拦安装（fail-soft 与运行时一致）；装了但版本不在枚举内照拦。
  pkg.peerDependenciesMeta[name] = { optional: true }
}
const pkgExpected = JSON.stringify(pkg, null, 2) + '\n'
// 发布版本唯一源 = root（selector 与 dsh.plugin.json 只镜像）。
const releaseVersion = pkg.version

// ── 2. selector package.json：内部一致性面（engines + 19 dsh-* peer + version） ──
const selUrl = new URL('packages/selector/package.json', ROOT)
const selOriginal = await read('packages/selector/package.json')
const sel = JSON.parse(selOriginal)
sel.engines ??= {}
sel.engines.dsh = peerRange
sel.peerDependencies ??= {}
sel.peerDependenciesMeta ??= {}
for (const name of selectorDshPeers) {
  sel.peerDependencies[name] = peerRange
  sel.peerDependenciesMeta[name] = { optional: true }
}
sel.version = releaseVersion // 陈旧 0.2.0 徽章修正（审计 B3/E）：随 root 版本镜像
const selExpected = JSON.stringify(sel, null, 2) + '\n'

// ── 3. selector dsh.plugin.json：engines + version 镜像 root ─────────────────
const pluginUrl = new URL('packages/selector/dsh.plugin.json', ROOT)
const pluginOriginal = await read('packages/selector/dsh.plugin.json')
const manifest = JSON.parse(pluginOriginal)
manifest.engines ??= {}
manifest.engines.dsh = peerRange
manifest.version = releaseVersion // 镜像源=root package.json（B3：五分支本就同步 root）
const manifestExpected = JSON.stringify(manifest, null, 2) + '\n'

// ── 4. 9 语 README：管理块（支持清单 + 运行时已验证清单） ────────────────────
const BEGIN = '<!-- host-compat:begin — generated by scripts/sync-hosts.mjs from scripts/hosts.mjs; DO NOT EDIT -->'
const END = '<!-- host-compat:end -->'
const versionList = supportedHosts.map((v) => `\`${v}\``).join(' ')
const LINES = '0.1.0 / 0.1.1 / 0.1.2 / 0.1.5 / 0.1.7 / 0.2.0'
const linesPerLang = {
  'README.md': [`- **Supported DSH hosts:** ${versionList} (${supportedHosts.length} rc releases across lines ${LINES})`],
  'README.zh.md': [`- **支持的 DSH 宿主：** ${versionList}（覆盖 ${LINES} 六条线共 ${supportedHosts.length} 个 rc）`],
  'README.de.md': [`- **Unterstützte DSH-Hosts:** ${versionList} (${supportedHosts.length} RC über die Linien ${LINES})`],
  'README.es.md': [`- **Hosts DSH compatibles:** ${versionList} (${supportedHosts.length} rc en las líneas ${LINES})`],
  'README.fr.md': [`- **Hôtes DSH pris en charge :** ${versionList} (${supportedHosts.length} rc sur les lignes ${LINES})`],
  'README.it.md': [`- **Host DSH supportati:** ${versionList} (${supportedHosts.length} rc attraverso le linee ${LINES})`],
  'README.ru.md': [`- **Поддерживаемые хосты DSH:** ${versionList} (${supportedHosts.length} rc по линиям ${LINES})`],
  'README.ja.md': [`- **対応する DSH ホスト:** ${versionList}（${LINES} の ${supportedHosts.length} rc）`],
  'README.ko.md': [`- **지원하는 DSH 호스트:** ${versionList} (${LINES} 라인의 ${supportedHosts.length}개 rc)`],
}
// 矩阵跑绿清单（.compat-results/verified.json，由矩阵执行体写出；Phase 5 前不存在则跳过）
const verifiedUrl = new URL('.compat-results/verified.json', ROOT)
if (existsSync(verifiedUrl)) {
  const { verified = [] } = JSON.parse(await readFile(verifiedUrl, 'utf8'))
  if (verified.length > 0) {
    const list = verified.map((v) => `\`${v}\``).join(', ')
    const verifiedLine = {
      'README.md': `- **Runtime-verified:** ${list} — evidence in \`.compat-results/\``,
      'README.zh.md': `- **运行时已验证：** ${list}（证据见 \`.compat-results/\`）`,
      'README.de.md': `- **Zur Laufzeit verifiziert:** ${list} — Nachweise in \`.compat-results/\``,
      'README.es.md': `- **Verificado en tiempo de ejecución:** ${list} — evidencia en \`.compat-results/\``,
      'README.fr.md': `- **Vérifié à l'exécution :** ${list} — preuves dans \`.compat-results/\``,
      'README.it.md': `- **Verificato a runtime:** ${list} — prove in \`.compat-results/\``,
      'README.ru.md': `- **Проверено на этапе выполнения:** ${list} — доказательства в \`.compat-results/\``,
      'README.ja.md': `- **ランタイム検証済み:** ${list}（証跡は \`.compat-results/\`）`,
      'README.ko.md': `- **런타임 검증됨:** ${list} (증적은 \`.compat-results/\`)`,
    }
    for (const [file, line] of Object.entries(verifiedLine)) linesPerLang[file].push(line)
  }
}
const readmeProblems = []
for (const [file, lines] of Object.entries(linesPerLang)) {
  const block = `${BEGIN}\n${lines.join('\n')}\n${END}`
  const url = new URL(`./${file}`, ROOT)
  const content = await readFile(url, 'utf8')
  const beginAt = content.indexOf(BEGIN)
  if (beginAt === -1) {
    // 插入点：第一个 `## ` 二级标题前
    const at = content.search(/^## /m)
    assert(at !== -1, `${file} 找不到插入锚点（第一个二级标题）`)
    if (write) {
      await writeFile(url, content.slice(0, at) + block + '\n\n' + content.slice(at))
      console.log(`write  ${file}: 插入管理块`)
    } else {
      readmeProblems.push(`${file} 缺少 host-compat 管理块`)
    }
    continue
  }
  const endAt = content.indexOf(END, beginAt)
  assert(endAt !== -1, `${file} 管理块缺少 end 标记`)
  const current = content.slice(beginAt, endAt + END.length)
  if (write) {
    if (current !== block) {
      await writeFile(url, content.slice(0, beginAt) + block + content.slice(endAt + END.length))
      console.log(`write  ${file}: 更新管理块`)
    } else {
      console.log(`ok     ${file}: 管理块已是最新`)
    }
  } else if (current !== block) {
    readmeProblems.push(`${file} 管理块内容需要同步`)
  } else {
    console.log(`ok     ${file}: 管理块已是最新`)
  }
}

// ── 5. 汇总校验/写盘 ────────────────────────────────────────────────────────
if (write) {
  if (pkgOriginal !== pkgExpected) {
    await writeFile(pkgUrl, pkgExpected)
    console.log('write  package.json (engines.dsh + 4 client peer 枚举=闸门面)')
  } else console.log('ok     package.json')
  if (selOriginal !== selExpected) {
    await writeFile(selUrl, selExpected)
    console.log('write  packages/selector/package.json (engines + dsh-* peer 枚举 + version 镜像)')
  } else console.log('ok     packages/selector/package.json')
  if (pluginOriginal !== manifestExpected) {
    await writeFile(pluginUrl, manifestExpected)
    console.log('write  packages/selector/dsh.plugin.json (engines.dsh + version 镜像 root)')
  } else console.log('ok     packages/selector/dsh.plugin.json')
  console.log('done   --write 完成')
} else {
  const jsonDrift = [
    ...(pkgOriginal !== pkgExpected ? ['package.json (engines.dsh / 4 client peer 枚举)'] : []),
    ...(selOriginal !== selExpected ? ['packages/selector/package.json (engines / dsh-* peer 枚举 / version)'] : []),
    ...(pluginOriginal !== manifestExpected ? ['packages/selector/dsh.plugin.json (engines / version)'] : []),
  ]
  if (jsonDrift.length === 0 && readmeProblems.length === 0) {
    console.log('ok     全部写点与 hosts.mjs 一致')
  } else {
    for (const p of [...jsonDrift, ...readmeProblems]) console.error(`drift  ${p}`)
    console.error('\n运行 node scripts/sync-hosts.mjs --write 修复')
    process.exit(1)
  }
}
